version: '3.8'

services:
  web:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.23-alpine
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    # No entrypoint override
    command: >
      certonly
       --non-interactive
       --agree-tos
       --no-eff-email
       --email your-email@example.com
       --webroot -w /var/www/certbot
       -d ecombackend.shop
       -d www.ecombackend.shop
      && nginx -s reload

volumes:
  certbot-etc:
  certbot-var:
