version: '3.8'

services:
  web:
    build:
      context: .
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - web

volumes:
  certbot-etc:
  certbot-var: